name: Android Build

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]
        android-api-level: [30]
        target-sdk: [30]
        build-tools: [30.0.3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ matrix.android-api-level }}
        target-sdk: ${{ matrix.target-sdk }}
        build-tools: ${{ matrix.build-tools }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
